### ISSUE TITLE
Use input xml with namespace

### ISSUE THREAD

**Issue by alejandrorivoir** [MichielCM/xsd2html2xml#1]
I found the solution very good.
When I use input xml without namespace it works fine but if the xml has a namespace then it does not work.
Thank you

**Comment by MichielCM** [comment]
Glad you like it!

It's true that namespaces are not supported at the moment. I'll take a look at it and see if I can add that feature.

**Comment by alejandrorivoir** [comment]
Excellent!!

I'll try to see how to add this feature to help with your work. '
regards

**Comment by MichielCM** [comment]
Just a heads up. I've investigated the issue and started working on a solution. It's quite a bit of work, but I hope to have a beta version up within the next week.

Could you share the XSD/XML files you're encountering problems with? Just to test if they'll work with the new code...

**Comment by MichielCM** [comment]
Alright, I've uploaded a new version that works with namespaces. The commit is only to this file:
https://github.com/MichielCM/xsd2html2xml/blob/master/xsd%2Bxml2html.xsl

I tested it with your files and it seems to work well. Can you confirm?

I also added support for loading namespaces from separate XSD files. The code needs some clean-up and testing, though. When I get around to that I'll do a proper release 1.1.

**Comment by MichielCM** [comment]
Oh, and before I forget: only the JavaScript option for generating the XML currently works, so not the XSLT one... ;)

**Comment by alejandrorivoir** [comment]
Hello Michiel, thank you very much for the adjustments. I was testing the new version and it works correctly.

**Comment by MichielCM** [comment]
Hi Alejandro,

I uploaded a new version with better support for namespaces. Would you test it please?

After running a few more tests, I'll release it as version 2.0.

Best regards,
Michiel

**Comment by alejandrorivoir** [comment]
Hi Michiel, great !!!
I'll try it and I'll let you know.
regards
