### ISSUE TITLE
inputs no terminated

### ISSUE THREAD

**Issue by matiasCo** [MichielCM/xsd2html2xml#10]
Hi!
I'm testing this project, using the examples. I have already generated the form with data using xsd+xml2html.xsl, but I'm having trouble using the html2xml.xsl.
When I use the result of the xsd+xml2html.xsl to html2xml.xsl, I get this error:

> The element type "input" must be terminated by the matching end-tag "</input>".

Inspecting the generated form using xsd+xml2html.xsl, I found that the input elements are never closed, this happens even on the [examples](https://htmlpreview.github.io/?https://github.com/MichielCM/xsd2html2xml/blob/master/examples/complex-sample/form.html).

Is this a bug or am I doing something wrong?

Regards,
Matias

**Comment by MichielCM** [comment]
Hi Matias,

In HTML, input elements should not be closed. In XHTML, they should. You are trying to run HTML through an XML processor, which results in the error you mentioned.

If you want to use html2xml, make sure to set output method in xsd+xml2html to 'xhtml'.

However, you don't really need html2xml. If you use xsd+xml2html with output method 'html' and config-xml-generator 'js' (the default values), JavaScript generates valid XML automatically. So unless you REALLY want to generate your final XML with XSLT, just use JavaScript and don't bother with html2xml.

Best regards,
Michiel

**Comment by matiasCo** [comment]
Thanks Michiel!
It worked using XHTML but, as you said, the output generated with JavaScript works better for me.

Regards,
Matias
