### ISSUE TITLE
xsd+xml2html.xsl data parameter as string

### ISSUE THREAD

**Issue by matiasCo** [MichielCM/xsd2html2xml#11]
Hi Michiel! Sorry to bother you again.

I have successfully generated a html using xsd+xml2html.xsl passing the path to my xml file as a parameter (xml-doc).
The problem is that I need to use xml data stored in a database so, instead passing the path to the xml file, is there a way I could pass the xml as a string parameter?

Thank you!

**Comment by MichielCM** [comment]
Hi Matias,

Yes, but it depends on your implementation. The XSLT does a document() call for a specific URI, expecting an XML document in return. By default, all XSLT processors resolve URIs by looking up the referenced files online or on the local file system. But you can write your own URI resolver to handle document() calls.

In one of my projects I used Xalan with a custom URIResolver class to load XML files from different sources. I imagine other XSLT processors have similar functionalities.

Best regards,
Michiel

**Comment by matiasCo** [comment]
That worked!
Thank you very much!
