### ISSUE TITLE
multiple form fields for elements in a base type defined in an included file

### ISSUE THREAD

**Issue by kgi-github** [MichielCM/xsd2html2xml#18]
I have an issue where elements defined in a base type (i.e. one which is extended be another type) appear multiple times in a form where they should only appear once. This only happens when the base type is defined in an included file. 

Again, I have simplified as much as possible.

I have two files. The first is Base.xsd:
```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:complexType name="BaseType">
		<xs:sequence>
			<xs:element name="baseField" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>
```

The second file is Extension.xsd:
```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:include schemaLocation="Base.xsd"/>
	
	<xs:complexType name="ExtensionType">
		<xs:complexContent>
			<xs:extension base="BaseType"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="MyType">
		<xs:sequence>
			<xs:element name="extensionField" type="ExtensionType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:element name="thing" type="MyType"/>
	
</xs:schema>
```

This produces a form with baseField appearing twice. If I change the type of "thing" to "ExtensionType" the error does not occur. If I define BaseType in the Extension.xsd file (instead of in the included Base.xsd file) the error does not occur.

This error occurs with Saxon HE 9.8 0.15 and Xalan 2.7.2.

**Comment by MichielCM** [comment]
The latest commit should fix it.

**Comment by kgi-github** [comment]
Thanks, fixes both issues. Shall I leave the closing of issues to you?
