### ISSUE TITLE
If an attribute uses an enumerated list, the first enumeration populates the attribute.

### ISSUE THREAD

**Issue by shanerigby** [MichielCM/xsd2html2xml#23]
A great project - thanks!

The use of an enumeration within an optional attribute should remain optional. At the moment, as soon as an element that contains an attribute that uses an enumerated list is loaded into the form, the first value from the list is populated in the form field.

 For example, for an attribute defined as follows: 
```xml
<xs:attribute name="IsCurrent" type="yesNoList" use="optional"/>
```
that uses the simpleType as follows:
```xml
	<xs:simpleType name="yesNoList">
		<xs:restriction base="xs:token">
			<xs:enumeration value="No"/>
			<xs:enumeration value="Yes"/>
		</xs:restriction>
	</xs:simpleType>
```
should not default to the first value in the enumerated list.

Is it possible to leave the form field empty (i.e. the optional attribute is not included in the output xml) until an enumeration is selected from the dropdown?

Thanks again!

**Comment by MichielCM** [comment]
Hi,

I've added a hotfix for this issue. In case an attribute is optional, a first option ('-') is added without a value. It is selected by default if no other option is specified with @default or @fixed. Users can always select it if they want to undo their previous selection.

Does it work for you?

Best regards,
Michiel

**Comment by shanerigby** [comment]
Thanks Michiel, 

Yes that works for me. I've tested the hot-fix and it looks great. 

Thanks again,

Shane
