### ISSUE TITLE
step attribute outside of element

### ISSUE THREAD

**Issue by Brassrat** [MichielCM/xsd2html2xml#34]
warnings running xslt:
[WARNING]: file:/build/upp/xsd2html2xml/utils/gui-attributes.xsl: line 418: Attribute 'step' outside of element.
[WARNING]: file:/build/upp/xsd2html2xml/utils/gui-attributes.xsl: line 429: Attribute 'step' outside of element.
[WARNING]: file:/build/upp/xsd2html2xml/utils/gui-attributes.xsl: line 440: Attribute 'step' outside of element.

**Comment by moravcik94** [comment]
how did you resolve it ?
