### ISSUE TITLE
XSLT newbie

### ISSUE THREAD

**Issue by sarah7777** [MichielCM/xsd2html2xml#4]
This project looks very useful; it might solve a pretty difficult task for me, although I'm having some initial issues getting up and running using the _xsd+xml2html.xls_ sheet. I'm a newbie to XSLT so not very familiar with how these things usually work. I've had some success with _xsd2html.xls_ but think that _xsd+xml2html.xls_ is really the one that I need to be using, so that the generated form can be pre-populated when required.

I'm currently trying it with a 30-day evaluation of Saxon PE since this seemed necessary to support the _dyn:evaluate_ function. However, I wonder if there's a free alternative?

The next problem that I'm having is difficulty resolving "Internal error: no value for variable $xml-doc" which presumably indicates that my _<xsl:copy-of select="document('values.xml')/*"/>_ isn't having any effect in the _xml-doc_ variable declaration. I can't seem to find any syntax that will successfully read my XML file here - have tried filename only, full path, forward slashes & back slashes (singles and doubles), adding _file:_ prefix. 

Can you offer any assistance please? Thanks!

**Comment by MichielCM** [comment]
Hi Sarah,

I haven't used the code with any XSLT product, just with my own implementation of Xerces. So I don't know the peculiarities of Saxon PE or why it doesn't work.

I can give you my own implementation as an executable JAR file?

I have been thinking about providing the code as an out-of-the-box Chrome extension or something similar, but that's still a work-in-progress...

**Comment by sarah7777** [comment]
Yes please, that JAR sounds like it would help!

**Comment by MichielCM** [comment]
Alright, here goes: https://github.com/MichielCM/xsd2html2xml/tree/master/app

Check out the JAR file. It requires JRE 1.8 installed to run. Use it from the command line like this:
java -jar xsd2html2xml.jar -dir c:\test\ -schema complex-sample.xsd -form form.htm -x false

**Comment by sarah7777** [comment]
Thank you. Trying your JAR now with the complex-sample as above. I'm getting "SystemId Unknown; Line #75; Column #16" so presumably I need to somehow set the SystemId for the Transformer instance?

**Comment by MichielCM** [comment]
No, that's just a console message displaying the contents of the XML file. You should have a generated form now in your working directory (-dir), form.htm?

**Comment by sarah7777** [comment]
Yep, it created a form.html output file! 

Okay, cool, I'll not worry about the console message and now try some of our own schemas.

**Comment by sarah7777** [comment]
Trying to transform our XSD schemas and XML files again, now using the JAR that you kindly provided. The stylesheet is successfully generating HTML forms as output, yet unfortunately they don't seem to be pre-populated from the XML files. 

On the console, I see the same messages for both sets of XSD+XML files:

SystemId Unknown; Line #16; Column #46; Unknown error in XPath.
SystemId Unknown; Line #75; Column #16

Maybe not easy to figure out the issue here - presumably the "Unknown error in XPath" our only clue? Sadly, I'm unable to share the XSD and XML input files. Sorry!

**Comment by MichielCM** [comment]
Did you change the file name for the XML document in xsd2html2xml.xsl? Line 16-46 in that file is the reference to the XML document: <xsl:copy-of select="document('complex-sample.xml')/*"/>

Are you sure you included the /* etc. in that reference? And is the file in the same directory? And is it valid XML?

Line 75-16 in xsd+xml2html.xsl is the output of the XML file that is written to the console. It's empty, so there's been some error in reading the file...

**Comment by sarah7777** [comment]
Yes, I changed the XML filename in the document reference. Found the problem now -- it's looking for the XML file inside the JAR. It opens and processes it successfully from there if I add it to the JAR. Hopefully it could be configured to read it directly from the local filesystem or (preferably) a webservice instead?

**Comment by MichielCM** [comment]
Good catch, I forgot to update that bit. :) Now the JAR reads the referenced files from the working directory (-dir) as well.

I'll take a look at the web service request if I get around to it. But I'm only providing the app as an example implementation of how to use it, not as a supported fully-fledged product.

**Comment by sarah7777** [comment]
Brilliant, thank you - and understood. I was hoping that reading the XML document from an http request instead of a file might just be a trivial adjustment to the _xml-doc_ declaration in the XLS but sounds like it's not that simple. Working with XSLT, XPATH, etc is all very new to me, so I don't yet have much understanding of how it works!

**Comment by MichielCM** [comment]
No problem, glad to help. I've been considering creating a small commercial implementation for this project, as an app or browser extension perhaps. I'll take your suggestions into account!

**Comment by sarah7777** [comment]
Hi again! Just letting you know that I've found what appears to be an issue with some elements of the generated HTML form when it's populated using an XML file. 

The schema that I'm using has several elements that are specified as _minOccurs="0"_ and restricted implicitly to maximum 1. The resulting HTML form is operating correctly when generated as an empty form, with the add (+) buttons becoming disabled once clicked to add an element, preventing more than 1 of each such element from being added. 

However, when I generate a pre-populated HTML form for the same schema, the add (+) buttons for the pre-existing elements are initially clickable, allowing multiple additional copies of each element to be added. These buttons are being generated with _data-xsd2html2xml-max="1"_ attributes (but not disabled) so I'm puzzled why the behaviour is different to the 'Recurring complex' element in your _complex-sample_ example (which does have its '+ Recurring complex' button initially disabled)!

**Comment by sarah7777** [comment]
I'm able to workaround the above issue by using a little jQuery to iterate over the add (+) buttons and apply the _data-xsd2html2xml-max_ in a similar way to the _clickAddButton()_ handler!

**Comment by MichielCM** [comment]
It's a bug. I forgot to check whether the add button needs to be disabled if maxOccurs is implicitly 1...

I'll upload a fix, but I want to test it a little beforehand. In the meantime, this should do it:

In the add-add-button template calls, replace this:
<xsl:when test="$nodes-count = @maxOccurs">true</xsl:when>
<xsl:otherwise>false</xsl:otherwise>

with this:
<xsl:when test="@maxOccurs and $nodes-count = @maxOccurs">true</xsl:when>
<xsl:when test="$nodes-count = 1">true</xsl:when>
<xsl:otherwise>false</xsl:otherwise>

**Comment by MichielCM** [comment]
The new versions of the XSL files contain the fix. Could you test it and check if it creates no new bugs?

**Comment by sarah7777** [comment]
Many thanks for the update. I've given this a try -- it works correctly for most elements however there's now an add button with _data-xsd2html2xml-max="8"_ which is initially disabled even though the form only contains 1 of these elements, so the button shouldn't be disabled in this case. If I use the previous revision of the stylesheet + workaround the form doesn't have this issue.

**Comment by MichielCM** [comment]
This should do it. In the add-add-button template calls, change:
`<xsl:when test="$nodes-count = 1">true</xsl:when>`

to:
`<xsl:when test="not(@maxOccurs) and $nodes-count = 1">true</xsl:when>`

**Comment by MichielCM** [comment]
Hi there! Just wanting to let you know I recently published a commercial implementation of this project that you might like. It removes the headache of getting the code to work by prepackaging all necessary components.

It does support some of the things we have discussed here, such as loading schemas from URLs and pre-configuring them. Like the test app I shared, it comes with a command line interface next to a GUI.

If you're interested, you can find it here: http://www.michielmeulendijk.nl/xml-schema-form-generator/

**Comment by sarah7777** [comment]
Thanks for the update. I used a ByteArrayInputStream substitution within the URLResolver to load our XML schemas, which might not be ideal but works successfully. I'm not actively developing code with XSLT transforms at the moment but thought it might be useful to feed back a few other issues that I worked around with changes to the stylesheets:

1) In the JavaScript code 'INITIAL CALLS' section o.closest(...) didn't appear to be valid for IE11 so this was replaced with the jQuery equivalent $(o).closest(...) together with a non-zero length check on the conditional and [0] index before previousElementSibling.

2) Several changes to resolve validation issues:
i) Modified creation of fieldset and label elements so that those with style="display: none" are also initially disabled. 
ii) Modified the clickAddButton() function so that it enables all new nodes added to the DOM and then either enables or disables their child input, select and textarea elements based upon the enabled/disabled status of their immediate parent. This was achieved by bringing forward the insertBefore() to follow cloneNode(), then newNode.removeAttribute("style") moved before the query loop and newNode.removeAttribute("disabled") added and included 'div' in the list of element types for the querySelectorAll(). Finally, the loop was modified accordingly (including using jQuery to remove 'disabled' class from an element if their parent was enabled).

3) Minor cosmetic changes such as emitting non-breaking spaces around checkboxes and the description value for legend elements.

Hope this makes sense as my notes were written a couple of months ago now!

**Comment by MichielCM** [comment]
Thanks for your feedback. Do you remember why you added the disabling code in #2? Which errors did it solve?

**Comment by sarah7777** [comment]
The validation issue that those changes fixed was to do with hidden ("display: none") child elements preventing the form from submitting; so they had to be disabled as well as hidden (at all levels) for the form to function correctly.

**Comment by MichielCM** [comment]
I found it and fixed it, thanks for getting back to me. I also added a few JavaScript polyfills for closest etc, taking care of #1.

You might consider switching to the new version. There've been a lot of bug fixes and updates in the last months.
