### ISSUE TITLE
When minOccurs attribute is missing (release 2.6)

### ISSUE THREAD

**Issue by JulienDD** [MichielCM/xsd2html2xml#8]
If minOccurs attribute is missing, the value of the count parameter in the template handle-complex-element is not correct when we want to fill the form with xml content.
At line 683, I suggest changing the code like this:

<xsl:with-param name="count">

<<xsl:choose>>

<xsl:when test="count(dyn:evaluate(concat('exsl:node-set($xml-doc)',$tree,'/*[name() = &quot;',$local-namespace-prefix,$id,'&quot;]'))) &gt; 0">

<xsl:value-of select="count(dyn:evaluate(concat('exsl:node-set($xml-doc)',$tree,'/*[name() = &quot;',$local-namespace-prefix,$id,'&quot;]')))" />

</xsl:when>

<xsl:when test="@minOccurs">

<xsl:value-of select="@minOccurs" />

</xsl:when>

<<xsl:otherwise>1</xsl:otherwise>

</xsl:choose>

</xsl:with-param>

**Comment by MichielCM** [comment]
Thanks for the suggestion. I have released a version 3 that uses JavaScript to fill the form and shouldn't have this problem.

If you want, you can push this bugfix and I'll accept it for version 2.x.
