### ISSUE TITLE
Unexpected results

### ISSUE THREAD

**Issue by AeroYves** [MichielCM/xsd2html2xml#9]
HI Michiel,

I try to convert the DOI XSD into HTML using your stylesheet,
Using the xsd2html tool in combination with xsltproc ( and with php's XSLTProcessor) on https://schema.datacite.org/meta/kernel-4.1/metadata.xsd the result is close to 100%. The only problems I see is that  <xs:complexType mixed="true">, <xs:complexType name="point"> and   <xs:complexType name="box"> yield weird results: A radiobutton followed by a text input. 
Since I a m quite the novice in this field, can you point me in a debug direction?

Kind regards,
Yves,

**Comment by MichielCM** [comment]
Hi Yves,

That's how xs:choice elements are rendered. geoLocation, for example, can contain either geoLocationPlace, geoLocationPoint, etc. I create radio buttons to present that choice. The longitudinalPoint elements are correctly rendered (expecting floats with numeric ranges set). I suppose that valid XML is generated, right?

You may want to use some JavaScript or CSS to automatically show box or point elements when a radio button is checked.

As for mixed="true". That's not supported. You can just enter text, but not intersperse text with elements. I've got it planned for a new release.
